services:
  database:
    image: postgres:15
    container_name: postgres_db
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydb"]
      interval: 3s
      timeout: 5s
      retries: 10
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  sanity:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sanity_app
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://myuser:mypass@database:5432/mydb
      NODE_ENV: production
      NEXTAUTH_URL: http://localhost:3000
      AUTH_TRUST_HOST: "true"
      AUTH_SECRET: ${AUTH_SECRET}
      CRONJOB_SECRET: ${CRONJOB_SECRET}
      AUTH_GOOGLE_ID: ${AUTH_GOOGLE_ID}
      AUTH_GOOGLE_SECRET: ${AUTH_GOOGLE_SECRET}
      AUTH_DISCORD_ID: ${AUTH_DISCORD_ID}
      AUTH_DISCORD_SECRET: ${AUTH_DISCORD_SECRET}
    command: sh -c "npx prisma migrate deploy && npm run start"
    depends_on:
      database:
        condition: service_healthy

volumes:
  postgres_data:
